version: '3.7'

services:
  py-sd:
    image: zuojianghua/stable-diffusion-docker-image
    ports:
      - "8800:8800"
      - "8888:8888"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./out:/workspace/out"  
      - "./cache:/root/.cache"
      - "./src/models:/workspace/models"  
      - "./labs:/workspace/labs"      
      - "./app.py:/workspace/app.py" 
    networks:
      - sdnet
    restart: always
    entrypoint: /bin/bash -c "pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && python /workspace/app.py"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  sdnet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
