name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0 # docker build & push
        with:
          context: .
          file: Dockerfile
          push: true
          tags: zuojianghua/stable-diffusion-docker-image:${{date +%Y%m%d}}
